"""UNIVID unified video moderation VLM (arXiv:2606.05748)."""

from ltx_trainer.univid.capbench import (
    CAPBENCH_DOMAIN_STATS,
    VKB_EXAMPLES,
    CapBenchSample,
    capbench_catalog,
    sample_capbench_cases,
)
from ltx_trainer.univid.config import UnividConfig
from ltx_trainer.univid.layout import LIMITATIONS
from ltx_trainer.univid.metrics import (
    EntailmentRelation,
    capbench_bundle,
    capbench_f1,
    event_precision,
    event_recall,
    non_violative_recall,
    violative_recall,
)
from ltx_trainer.univid.mock import (
    ToyUnividCaptioner,
    evaluation_smoke,
    run_capbench_smoke,
    run_lite_rag_smoke,
    run_risk_filter_smoke,
    run_trend_smoke,
)
from ltx_trainer.univid.moderation import (
    FusionNetwork,
    LiteDecision,
    ModerationDecision,
    PolicyHeadConfig,
    RiskFilter,
    RiskFilterResult,
    TrendHead,
    UnividLite,
    UnividRAG,
    VideoSignals,
    ViolationKnowledgeBase,
)
from ltx_trainer.univid.pipeline import (
    benchmarks_bundle,
    evaluation_demo,
    framework_card,
    pipeline_demo,
    table_i_training_stages,
    table_ii_capbench_comparison,
    table_iii_capbench_results,
    table_iv_deployment_cost,
    table_v_risk_filter_ablation,
    table_vi_moderation_actor_ablation,
    table_vii_capbench_domain_stats,
    table_viii_architecture_ablation,
    table_ix_training_hyperparams,
)
from ltx_trainer.univid.prompts import (
    CAPTION_INSTRUCTION,
    CAPTION_PROMPT,
    ENTAILMENT_JUDGMENT_TEMPLATE,
    EVENT_EXTRACTION_TEMPLATE,
    format_lite_prompt,
    format_rag_prompt,
    prompt_bundle,
)

__all__ = [
    "CAPBENCH_DOMAIN_STATS",
    "CAPTION_INSTRUCTION",
    "CAPTION_PROMPT",
    "ENTAILMENT_JUDGMENT_TEMPLATE",
    "EVENT_EXTRACTION_TEMPLATE",
    "CapBenchSample",
    "EntailmentRelation",
    "FusionNetwork",
    "LIMITATIONS",
    "LiteDecision",
    "ModerationDecision",
    "PolicyHeadConfig",
    "RiskFilter",
    "RiskFilterResult",
    "ToyUnividCaptioner",
    "TrendHead",
    "UnividConfig",
    "UnividLite",
    "UnividRAG",
    "VKB_EXAMPLES",
    "VideoSignals",
    "ViolationKnowledgeBase",
    "benchmarks_bundle",
    "capbench_bundle",
    "capbench_catalog",
    "capbench_f1",
    "evaluation_demo",
    "evaluation_smoke",
    "event_precision",
    "event_recall",
    "format_lite_prompt",
    "format_rag_prompt",
    "framework_card",
    "non_violative_recall",
    "pipeline_demo",
    "prompt_bundle",
    "run_capbench_smoke",
    "run_lite_rag_smoke",
    "run_risk_filter_smoke",
    "run_trend_smoke",
    "sample_capbench_cases",
    "table_i_training_stages",
    "table_ii_capbench_comparison",
    "table_iii_capbench_results",
    "table_iv_deployment_cost",
    "table_v_risk_filter_ablation",
    "table_vi_moderation_actor_ablation",
    "table_vii_capbench_domain_stats",
    "table_viii_architecture_ablation",
    "table_ix_training_hyperparams",
    "violative_recall",
]
