"""NPC: finite-blocklength bounds for noisy permutation channels (Feng et al., arXiv:2605.25699)."""

from ltx_trainer.npc.bounds import (
    epsilon_capacity,
    gaussian_approx_log_m_3x4,
    gaussian_approx_log_m_bsc,
    log_m_star_achievability_lower,
    log_m_star_converse_upper,
    meta_converse_eta,
    meta_converse_penalty,
    normalized_rate,
)
from ltx_trainer.npc.config import NPCConfig
from ltx_trainer.npc.gaussian import (
    average_gaussian_union,
    bsc_average_union,
    channel_3x4_variance,
    lattice_gaussian_average,
    normal_cdf,
    normal_ppf,
    solve_bsc_c_epsilon,
    solve_c_epsilon,
    transfer_direction_pairs,
    transfer_tail_prob,
)
from ltx_trainer.npc.geometry import (
    affine_output_dimension,
    bsc_relative_volume_ratio,
    channel_3x4_affine_map,
    channel_3x4_coordinate_map,
    channel_3x4_example,
    channel_3x4_kw_bounds,
    channel_3x4_relative_volume_ratio,
    channel_3x4_transfer_variance,
    log_kl_covering_bound,
    log_message_count_leading,
    log_stars_and_bars,
    num_transfer_directions,
    output_polytope_vertices,
    pmin,
    row_stochastic,
    stars_and_bars_count,
)
from ltx_trainer.npc.lattice import (
    elementary_transfer_violation,
    empirical_coordinate_3x4,
    enumerate_simplex_lattice,
    filter_kw_3x4,
    monte_carlo_decode_error,
    nearest_neighbor_decode,
)
from ltx_trainer.npc.pipeline import (
    bsc_rate_points,
    channel_3x4_rate_points,
    evaluation_demo,
    framework_card,
    table_main_results,
)

__all__ = [
    "NPCConfig",
    "affine_output_dimension",
    "average_gaussian_union",
    "bsc_average_union",
    "bsc_rate_points",
    "bsc_relative_volume_ratio",
    "channel_3x4_affine_map",
    "channel_3x4_coordinate_map",
    "channel_3x4_example",
    "channel_3x4_kw_bounds",
    "channel_3x4_rate_points",
    "channel_3x4_relative_volume_ratio",
    "channel_3x4_transfer_variance",
    "channel_3x4_variance",
    "elementary_transfer_violation",
    "empirical_coordinate_3x4",
    "enumerate_simplex_lattice",
    "epsilon_capacity",
    "evaluation_demo",
    "filter_kw_3x4",
    "framework_card",
    "gaussian_approx_log_m_3x4",
    "gaussian_approx_log_m_bsc",
    "lattice_gaussian_average",
    "log_kl_covering_bound",
    "log_m_star_achievability_lower",
    "log_m_star_converse_upper",
    "log_message_count_leading",
    "log_stars_and_bars",
    "meta_converse_eta",
    "meta_converse_penalty",
    "monte_carlo_decode_error",
    "nearest_neighbor_decode",
    "normal_cdf",
    "normal_ppf",
    "normalized_rate",
    "num_transfer_directions",
    "output_polytope_vertices",
    "pmin",
    "row_stochastic",
    "solve_bsc_c_epsilon",
    "solve_c_epsilon",
    "stars_and_bars_count",
    "table_main_results",
    "transfer_direction_pairs",
    "transfer_tail_prob",
]
